language: haskell

env:
  matrix:
    - HPVER=2012.4.0.0
    - HPVER=2013.2.0.0
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=head
  global:
    - CABALVER=1.18
    - HEAD_DEPS="diagrams-core diagrams-lib diagrams-solve"

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-svg\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
